/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProximosVencimentosRouteImport } from './routes/proximos-vencimentos'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as EmRiscoRouteImport } from './routes/em-risco'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpresasIdRouteImport } from './routes/empresas.$id'
import { Route as ClienteIdPainelRouteImport } from './routes/cliente.$id.painel'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProximosVencimentosRoute = ProximosVencimentosRouteImport.update({
  id: '/proximos-vencimentos',
  path: '/proximos-vencimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmRiscoRoute = EmRiscoRouteImport.update({
  id: '/em-risco',
  path: '/em-risco',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasIdRoute = EmpresasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmpresasRoute,
} as any)
const ClienteIdPainelRoute = ClienteIdPainelRouteImport.update({
  id: '/cliente/$id/painel',
  path: '/cliente/$id/painel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/em-risco': typeof EmRiscoRoute
  '/empresas': typeof EmpresasRouteWithChildren
  '/historico': typeof HistoricoRoute
  '/proximos-vencimentos': typeof ProximosVencimentosRoute
  '/relatorios': typeof RelatoriosRoute
  '/empresas/$id': typeof EmpresasIdRoute
  '/cliente/$id/painel': typeof ClienteIdPainelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/em-risco': typeof EmRiscoRoute
  '/empresas': typeof EmpresasRouteWithChildren
  '/historico': typeof HistoricoRoute
  '/proximos-vencimentos': typeof ProximosVencimentosRoute
  '/relatorios': typeof RelatoriosRoute
  '/empresas/$id': typeof EmpresasIdRoute
  '/cliente/$id/painel': typeof ClienteIdPainelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/em-risco': typeof EmRiscoRoute
  '/empresas': typeof EmpresasRouteWithChildren
  '/historico': typeof HistoricoRoute
  '/proximos-vencimentos': typeof ProximosVencimentosRoute
  '/relatorios': typeof RelatoriosRoute
  '/empresas/$id': typeof EmpresasIdRoute
  '/cliente/$id/painel': typeof ClienteIdPainelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/contratos'
    | '/em-risco'
    | '/empresas'
    | '/historico'
    | '/proximos-vencimentos'
    | '/relatorios'
    | '/empresas/$id'
    | '/cliente/$id/painel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/contratos'
    | '/em-risco'
    | '/empresas'
    | '/historico'
    | '/proximos-vencimentos'
    | '/relatorios'
    | '/empresas/$id'
    | '/cliente/$id/painel'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/contratos'
    | '/em-risco'
    | '/empresas'
    | '/historico'
    | '/proximos-vencimentos'
    | '/relatorios'
    | '/empresas/$id'
    | '/cliente/$id/painel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContratosRoute: typeof ContratosRoute
  EmRiscoRoute: typeof EmRiscoRoute
  EmpresasRoute: typeof EmpresasRouteWithChildren
  HistoricoRoute: typeof HistoricoRoute
  ProximosVencimentosRoute: typeof ProximosVencimentosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ClienteIdPainelRoute: typeof ClienteIdPainelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proximos-vencimentos': {
      id: '/proximos-vencimentos'
      path: '/proximos-vencimentos'
      fullPath: '/proximos-vencimentos'
      preLoaderRoute: typeof ProximosVencimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/em-risco': {
      id: '/em-risco'
      path: '/em-risco'
      fullPath: '/em-risco'
      preLoaderRoute: typeof EmRiscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/$id': {
      id: '/empresas/$id'
      path: '/$id'
      fullPath: '/empresas/$id'
      preLoaderRoute: typeof EmpresasIdRouteImport
      parentRoute: typeof EmpresasRoute
    }
    '/cliente/$id/painel': {
      id: '/cliente/$id/painel'
      path: '/cliente/$id/painel'
      fullPath: '/cliente/$id/painel'
      preLoaderRoute: typeof ClienteIdPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EmpresasRouteChildren {
  EmpresasIdRoute: typeof EmpresasIdRoute
}

const EmpresasRouteChildren: EmpresasRouteChildren = {
  EmpresasIdRoute: EmpresasIdRoute,
}

const EmpresasRouteWithChildren = EmpresasRoute._addFileChildren(
  EmpresasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContratosRoute: ContratosRoute,
  EmRiscoRoute: EmRiscoRoute,
  EmpresasRoute: EmpresasRouteWithChildren,
  HistoricoRoute: HistoricoRoute,
  ProximosVencimentosRoute: ProximosVencimentosRoute,
  RelatoriosRoute: RelatoriosRoute,
  ClienteIdPainelRoute: ClienteIdPainelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
